logging:
  level:
    cce: INFO
    org:
      springframework:
        ws: DEBUG
client.ssl.trust-store: classpath:truststore.jks
client.ssl.trust-store-password: changeit
client.ssl.key-store: jems-client.jks
client.ssl.key-store-alias: client
client.ssl.key-store-password: changeit
client.ws:
  url: 'https://ws.jnet.beta.pa.gov/logs'
  mq: 'http://10.1.26.48:3000/Post/Message\?mq-host\=OACTCAPS228.PA.LCL\&mq-port\=17006\&mq-manager\=QM_JNET_ISB\&mq-queue\=CCE.INBOUND.QUEUE'
